# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
